# Generated by Django 2.1.3 on 2018-11-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Confession', models.TextField()),
                ('image', models.FileField(upload_to='pictures/')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Confession.Confession'),
        ),
    ]
