# Generated by Django 2.1.3 on 2018-11-11 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 10, 7, 39, 52836, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='confession',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 10, 7, 39, 52471, tzinfo=utc)),
        ),
    ]
