# Generated by Django 2.1.3 on 2018-11-12 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0002_auto_20181111_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 23, 27, 7, 332103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='confession',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 23, 27, 7, 331753, tzinfo=utc)),
        ),
    ]
