# Generated by Django 2.1.3 on 2018-11-12 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0003_auto_20181112_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='categories',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Confession.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 23, 41, 25, 56243, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='confession',
            name='image',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 23, 41, 25, 55799, tzinfo=utc)),
        ),
    ]
