# Generated by Django 2.1.3 on 2018-11-14 00:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0004_auto_20181112_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AlterField(
            model_name='confession',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 0, 11, 58, 495920, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
